# Generated by Django 3.2.6 on 2021-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0004_postplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postplan',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(verbose_name='Application Link'),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='link',
            field=models.URLField(verbose_name='Application Link'),
        ),
    ]
