# Generated by Django 3.2.6 on 2021-08-11 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0005_auto_20210811_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplan',
            name='last_app_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last Date to Apply'),
            preserve_default=False,
        ),
    ]
