# Generated by Django 3.2.6 on 2021-08-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0013_postusersett'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postusersett',
            name='link',
            field=models.URLField(verbose_name='Link for websites'),
        ),
    ]
