# Generated by Django 3.2.6 on 2021-08-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0014_alter_postusersett_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='free_text',
            field=models.BooleanField(default=False, verbose_name='Add free text'),
        ),
        migrations.AddField(
            model_name='post',
            name='free_text_field',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postusersett',
            name='link',
            field=models.URLField(verbose_name='Link to websites'),
        ),
    ]
