# Generated by Django 3.2.6 on 2021-08-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0015_auto_20210823_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='free_text',
        ),
    ]
