# Generated by Django 3.2.6 on 2021-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0016_remove_post_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ws_activity',
            field=models.CharField(choices=[('1', 'Work application'), ('2', 'Registration of interest'), ('3', 'Other activity')], default=1, max_length=3),
        ),
    ]
