# Generated by Django 3.2.6 on 2021-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0017_post_ws_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ws_activity',
            new_name='choises_activity',
        ),
    ]
