# Generated by Django 3.2.6 on 2021-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0019_alter_post_choises_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplan',
            name='choises_activity',
            field=models.CharField(choices=[('Work application', 'Work application'), ('Registration of interest', 'Registration of interest'), ('Other activity', 'Other activity')], default='Work application', max_length=25),
        ),
        migrations.AddField(
            model_name='postplan',
            name='free_text_field',
            field=models.TextField(blank=True),
        ),
    ]
