# Generated by Django 3.2.6 on 2021-09-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0020_auto_20210823_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='Name of city', max_length=255),
        ),
    ]
