# Generated by Django 3.2.6 on 2021-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0021_post_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplan',
            name='city',
            field=models.CharField(default='Name of city', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
