# Generated by Django 3.2.6 on 2021-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksearch', '0022_auto_20210909_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='postusersett',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
